name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Unit tests - Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dnest4
      run: |
        python -m pip install numpy scipy cython setuptools
        git clone https://github.com/eggplantbren/DNest4.git
        cd DNest4/code
        make
        cd ..
        python setup.py install
    - name: Install dnest4-bilby
      run: |
        pip install .[test]
    - name: Test with pytest
      run: |
        python -m pytest
